CREATE TABLE runners (
  ten_k float,
  name VARCHAR(200),
  division VARCHAR(200),
  twenty_five_k float,
  gender VARCHAR(1),
  age integer,
  official varchar(200),
  bib varchar(8),
  genderdiv varchar(100),
  ctz VARCHAR(200),
  thirty_five_k float,
  overall float,
  pace float,
  state VARCHAR(200),
  thirty_k float,
  five_k float,
  half float,
  twenty_k float,
  country VARCHAR(200),
  city VARCHAR(200),
  forty_k float
);
